"""empty message

Revision ID: ac0d0e5eb574
Revises: 
Create Date: 2022-08-21 12:30:34.242701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0d0e5eb574'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'pwd',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user', 'distr',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['pwd'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'distr',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'pwd',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
